twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/assets/styles': styles
    globals:
        main_navigation: '%app.main_navigation%'

when@test:
    twig:
        strict_variables: true
