home_controller:
    resource: ../src/Controller/HomeController.php
    type: attribute

receive_controller:
    resource: ../src/Controller/ReceiveController.php
    type: attribute

script_controller:
    resource: ../src/Controller/ScriptController.php
    type: attribute

consent_script_controller:
    resource: ../src/Controller/ConsentScriptController.php
    type: attribute

tag_script_controller:
    resource: ../src/Controller/TagScriptController.php
    type: attribute

health_controller:
    resource: ../src/Controller/HealthController.php
    type: attribute

branding_logo_controller:
    resource: ../src/Controller/BrandingLogoController.php
    type: attribute

branding_theme_controller:
    resource: ../src/Controller/BrandingThemeController.php
    type: attribute

internal_traffic_public_controller:
    resource: ../src/Controller/InternalTrafficPublicController.php
    type: attribute
